domain: test-services-web-project.cours-ethem.dns-dynamic.net

replicaCount:
  mariadb: 1
  wordpress: 1

# TLS local auto-signé
tls:
  enabled: true
  issuer: selfsigned
  secretName: webproject-tls

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

# HPA léger en local
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

# Ressources un peu plus light en dev
resources:
  wordpress:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  mariadb:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "1", memory: "1Gi" }
