# webproject/values.local.yaml
# ----------------------------
# Spécifique au poste local / cluster k3s/microk8s/kind

# Domaine local → /etc/hosts
domain: test-services-web-project.cours-ethem.dns-dynamic.net

# Réplicas : pas de RWX local => 1 seul WordPress (cohérent et stable)
replicaCount:
  mariadb: 1
  wordpress: 1      # <= local
  nginx: 2

# Exposition : NodePort en local (en AWS on passera via Ingress/NLB/ALB)
nginxService:
  type: NodePort
  nodePort:
    http: 30080
    https: 30443

# TLS local : self-signed depuis le chart (déjà présent dans templates/secrets-nginx-ssl.yaml)
ssl:
  secretName: nginx-ssl

# Désactive ACME/cert-manager en local
acme:
  enabled: false

# ServiceAccount (on l’utilise dans les Deployments)
serviceAccount:
  create: true
  name: webproject

# (Optionnel) Ressources légères pour éviter le throttle en local
resources:
  wordpress:
    requests: { cpu: "50m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  nginx:
    requests: { cpu: "50m", memory: "64Mi" }
    limits:   { cpu: "500m", memory: "256Mi" }
  mariadb:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "1", memory: "1Gi" }
