# Domaine commun
domain: test-services-web-project.cours-ethem.dns-dynamic.net

# Réplicas : HPA gère WordPress → laisser 1 minimum
replicaCount:
  mariadb: 1
  wordpress: 1

# 3. Image registry & names
image:
  registry: docker.io/ethembektas
  mariadb: mariadb:latest
  wordpress: wordpress:latest

serviceAccount:
  create: true
  name: webproject

# Ressources (HPA requiert des requests CPU)
resources:
  wordpress:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  mariadb:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "1", memory: "1Gi" }

# MariaDB PVC
mariadb:
  storageClass: local-path
  storage: 10Gi


# Ingress uniquement HTTPS (pas de redirection HTTP)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

# TLS actif (self-signed local ; ACME plus tard)
tls:
  enabled: true
  issuer: selfsigned
  secretName: webproject-tls

# Autoscaling WordPress
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Salts WordPress secrets DB
secrets:
  db:
    name: db-credentials
  salts:
    name: wordpress-salts


externalSecrets:
  enabled: false
  region: ""   # non use en local




