image:
  registry: docker.io/ethembektas
  mariadb: mariadb:latest
  wordpress: wordpress:latest

replicaCount:
  mariadb: 1
  wordpress: 1
  nginx: 2

secrets:
  create: true   # le chart crée les 3 secrets s'il reçoit les valeurs nécessaires

  db:
    root: ""     # RENSEIGNÉ AU DEPLOIEMENT (jamais commité)

  wpA:
    database: "wp_a"
    username: "wp_a"
    password: "" # RENSEIGNÉ AU DEPLOIEMENT

  wpB:
    database: "wp_b"
    username: "wp_b"
    password: "" # RENSEIGNÉ AU DEPLOIEMENT

  # SALTS — "comme avant" :
  # - si existingSecretName est NON vide : on NE crée PAS le secret, WP le référence tel quel
  # - sinon : Helm crée/maintient le secret ; si déjà présent dans le cluster, il est réutilisé (lookup).
  # - champs ci-dessous (AUTH_KEY, etc.) restent vides -> génération aléatoire via randAlphaNum
  wpASalts:
    existingSecretName: ""   # ex: "mon-secret-salts-a" pour réutiliser un secret déjà créé à la main
    AUTH_KEY: ""
    SECURE_AUTH_KEY: ""
    LOGGED_IN_KEY: ""
    NONCE_KEY: ""
    AUTH_SALT: ""
    SECURE_AUTH_SALT: ""
    LOGGED_IN_SALT: ""
    NONCE_SALT: ""

  wpBSalts:
    existingSecretName: ""
    AUTH_KEY: ""
    SECURE_AUTH_KEY: ""
    LOGGED_IN_KEY: ""
    NONCE_KEY: ""
    AUTH_SALT: ""
    SECURE_AUTH_SALT: ""
    LOGGED_IN_SALT: ""
    NONCE_SALT: ""
