domains:
  a: blog1-services-web-project.cours-ethem.dns-dynamic.net
  b: blog2-services-web-project.cours-ethem.dns-dynamic.net

secrets:
  db:
    root: "change_me_root"

  wpA:
    database: "wp_a"
    username: "wp_a"
    password: "CHANGE_ME_PASS_A"

  wpB:
    database: "wp_b"
    username: "wp_b"
    password: "CHANGE_ME_PASS_B"

  wpASalts:
    AUTH_KEY: "A_xxx"
    SECURE_AUTH_KEY: "A_xxx"
    LOGGED_IN_KEY: "A_xxx"
    NONCE_KEY: "A_xxx"
    AUTH_SALT: "A_xxx"
    SECURE_AUTH_SALT: "A_xxx"
    LOGGED_IN_SALT: "A_xxx"
    NONCE_SALT: "A_xxx"

  wpBSalts:
    AUTH_KEY: "B_xxx"
    SECURE_AUTH_KEY: "B_xxx"
    LOGGED_IN_KEY: "B_xxx"
    NONCE_KEY: "B_xxx"
    AUTH_SALT: "B_xxx"
    SECURE_AUTH_SALT: "B_xxx"
    LOGGED_IN_SALT: "B_xxx"
    NONCE_SALT: "B_xxx"
