apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      access_log /var/log/nginx/access.log;

      server {
        listen 80;
        server_name test-services-web-project.cours-ethem.dns-dynamic.net;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name test.local;

        ssl_certificate      /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key  /etc/nginx/ssl/privkey.pem;

        location / {
          proxy_pass         http://wordpress-service:80;
          proxy_set_header   Host $http_host;
          proxy_set_header   X-Real-IP $remote_addr;
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"user nginx;\nworker_processes auto;\nerror_log /var/log/nginx/error.log warn;\n\nevents {\n  worker_connections 1024;\n}\n\nhttp {\n  include /etc/nginx/mime.types;\n  default_type application/octet-stream;\n  access_log /var/log/nginx/access.log;\n\n  server {\n    listen 80;\n    server_name test-services-web-project.cours-ethem.dns-dynamic.net;\n    return 301 https://$host$request_uri;\n  }\n\n  server {\n    listen 443 ssl;\n    server_name test.local;\n\n    ssl_certificate      /etc/nginx/ssl/fullchain.pem;\n    ssl_certificate_key  /etc/nginx/ssl/privkey.pem;\n\n    location / {\n      proxy_pass         http://wordpress-service:80;\n      proxy_set_header   Host $http_host;\n      proxy_set_header   X-Real-IP $remote_addr;\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-config","namespace":"default"}}
  name: nginx-config
  namespace: default
