apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: docker.io/ethembektas/wordpress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb-service
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        # SALT WordPress injectés depuis le Secret "wordpress-salts"
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: AUTH_KEY
        - name: SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: SECURE_AUTH_KEY
        - name: LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: LOGGED_IN_KEY
        - name: NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: NONCE_KEY
        - name: AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: AUTH_SALT
        - name: SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: SECURE_AUTH_SALT
        - name: LOGGED_IN_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: LOGGED_IN_SALT
        - name: NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-salts
              key: NONCE_SALT
