{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-salts-sync
  namespace: default
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: {{ .Values.wordpressSalts.name | default "wordpress-salts" }}
    creationPolicy: Owner
  data:
    - secretKey: AUTH_KEY
      remoteRef: { key: "webproject/salts", property: "AUTH_KEY" }
    - secretKey: SECURE_AUTH_KEY
      remoteRef: { key: "webproject/salts", property: "SECURE_AUTH_KEY" }
    - secretKey: LOGGED_IN_KEY
      remoteRef: { key: "webproject/salts", property: "LOGGED_IN_KEY" }
    - secretKey: NONCE_KEY
      remoteRef: { key: "webproject/salts", property: "NONCE_KEY" }
    - secretKey: AUTH_SALT
      remoteRef: { key: "webproject/salts", property: "AUTH_SALT" }
    - secretKey: SECURE_AUTH_SALT
      remoteRef: { key: "webproject/salts", property: "SECURE_AUTH_SALT" }
    - secretKey: LOGGED_IN_SALT
      remoteRef: { key: "webproject/salts", property: "LOGGED_IN_SALT" }
    - secretKey: NONCE_SALT
      remoteRef: { key: "webproject/salts", property: "NONCE_SALT" }
{{- end }}
