{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: {{ .Values.dbCredentials.name | default "db-credentials" }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef: { key: "webproject/db", property: "username" }
    - secretKey: root-password
      remoteRef: { key: "webproject/db", property: "root-password" }
    - secretKey: database
      remoteRef: { key: "webproject/db", property: "database" }
    - secretKey: wp-password
      remoteRef: { key: "webproject/db", property: "wp-password" }
{{- end }}
