{{- if and .Values.ingress.enabled .Values.tls.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webproject
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
      secretName: {{ .Values.tls.secretName | quote }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
{{- end }}
