{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webproject
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- /* En local: cert-manager gère TLS via Secret; en ALB: TLS à l’ALB → pas de spec.tls */ -}}
  {{- if and .Values.tls.enabled (ne .Values.ingress.className "alb") }}
  tls:
    - hosts: [ {{ .Values.domain | quote }} ]
      secretName: {{ .Values.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
{{- end }}
