apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;

    events { worker_connections 1024; }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      access_log /var/log/nginx/access.log;

      # --- Redirige tout HTTP vers HTTPS
      server {
        listen 80;
        server_name {{ .Values.domain }};
        return 301 https://$host$request_uri;
      }

      # --- HTTPS avec terminaison TLS + proxy vers WordPress
      server {
        listen 443 ssl;
        server_name {{ .Values.domain }};

        ssl_certificate      /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key  /etc/nginx/ssl/privkey.pem;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  10m;

        location / {
          proxy_pass         http://wordpress-service:80;
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
        }
      }
    }
