apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a-deployment
  labels: { app: nginx-a }
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector: { matchLabels: { app: nginx-a } }
  template:
    metadata: { labels: { app: nginx-a } }
    spec:
      serviceAccountName: {{ include "webproject.serviceAccountName" . }}
      containers:
      - name: nginx
        image: {{ printf "%s/%s" .Values.image.registry .Values.image.nginx }}
        imagePullPolicy: Always
        ports: [ { containerPort: 80 } ]
        livenessProbe:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        {{- with .Values.resources.nginx }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap: { name: nginx-a-config }
