apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.nginxService.type | default "NodePort" }}
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    {{- if eq (.Values.nginxService.type | default "NodePort") "NodePort" }}
    nodePort: {{ .Values.nginxService.nodePort.http }}
    {{- end }}
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    {{- if eq (.Values.nginxService.type | default "NodePort") "NodePort" }}
    nodePort: {{ .Values.nginxService.nodePort.https }}
    {{- end }}
