apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort.http }}
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: {{ .Values.service.nodePort.https }}
