{{- if not .Values.externalSecrets.enabled }}
{{- $name := required "values.secrets.db.name is required (local)" .Values.secrets.db.name }}
{{- $ex := (lookup "v1" "Secret" .Release.Namespace $name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
stringData:
  username:      {{ if $ex }}{{ index $ex.data "username"      | b64dec | quote }}{{ else }}"wp_user"{{ end }}
  root-password: {{ if $ex }}{{ index $ex.data "root-password" | b64dec | quote }}{{ else }}"change_me_root"{{ end }}
  database:      {{ if $ex }}{{ index $ex.data "database"      | b64dec | quote }}{{ else }}"wordpress"{{ end }}
  wp-password:   {{ if $ex }}{{ index $ex.data "wp-password"   | b64dec | quote }}{{ else }}"motdepasse_wp"{{ end }}
{{- end }}
