{{- if .Values.externalSecrets.enabled }}
{{- $region := required "values.externalSecrets.region is required when externalSecrets.enabled=true" .Values.externalSecrets.region }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-sm
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ $region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: eso
            namespace: external-secrets
{{- end }}
