{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webproject.dbSecretName" . }}
  labels: {{- include "webproject.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: mariadb-service

  DB_ROOT_PASSWORD: {{ required "secrets.db.root is required" .Values.secrets.db.root | quote }}

  DB_A_NAME:     {{ default "wp_a" .Values.secrets.wpA.database | quote }}
  DB_A_USER:     {{ default "wp_a" .Values.secrets.wpA.username | quote }}
  DB_A_PASSWORD: {{ required "secrets.wpA.password is required" .Values.secrets.wpA.password | quote }}

  DB_B_NAME:     {{ default "wp_b" .Values.secrets.wpB.database | quote }}
  DB_B_USER:     {{ default "wp_b" .Values.secrets.wpB.username | quote }}
  DB_B_PASSWORD: {{ required "secrets.wpB.password is required" .Values.secrets.wpB.password | quote }}
{{- end }}
