apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbCredentials.name }}
type: Opaque
stringData:
  username: {{ .Values.dbCredentials.username | quote }}
  password: {{ .Values.dbCredentials.password | quote }}
  root-password: {{ .Values.dbCredentials.password | quote }}
