apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssl.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  fullchain.pem: {{ .Files.Get "certs/fullchain.pem" | b64enc }}
  privkey.pem:   {{ .Files.Get "certs/privkey.pem"   | b64enc }}
