{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-sm
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: eso
            namespace: external-secrets
{{- end }}
