apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-b-deployment
  labels: { app: wordpress-b }
spec:
  replicas: {{ .Values.replicaCount.wordpress }}
  selector: { matchLabels: { app: wordpress-b } }
  template:
    metadata: { labels: { app: wordpress-b } }
    spec:
      serviceAccountName: {{ include "webproject.serviceAccountName" . }}
      initContainers:
      - name: wait-db
        image: busybox:1.36
        command: ['sh','-lc','for i in $(seq 1 120); do nc -z mariadb-service 3306 && exit 0; echo waiting-db; sleep 1; done; exit 1']
      containers:
      - name: wordpress
        image: {{ printf "%s/%s" .Values.image.registry .Values.image.wordpress }}
        imagePullPolicy: IfNotPresent
        ports: [ { containerPort: 80, name: http } ]
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom: { secretKeyRef: { name: {{ include "webproject.dbSecretName" . }}, key: DB_HOST } }
          - name: WORDPRESS_DB_NAME
            valueFrom: { secretKeyRef: { name: {{ include "webproject.dbSecretName" . }}, key: DB_B_NAME } }
          - name: WORDPRESS_DB_USER
            valueFrom: { secretKeyRef: { name: {{ include "webproject.dbSecretName" . }}, key: DB_B_USER } }
          - name: WORDPRESS_DB_PASSWORD
            valueFrom: { secretKeyRef: { name: {{ include "webproject.dbSecretName" . }}, key: DB_B_PASSWORD } }
        envFrom:
          - secretRef: { name: {{ include "webproject.wpBSalts.name" . }} }
        readinessProbe: { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 20, periodSeconds: 10, timeoutSeconds: 3, failureThreshold: 6 }
        livenessProbe:  { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 45, periodSeconds: 15, timeoutSeconds: 3, failureThreshold: 5 }
