apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels: { app: wordpress }
spec:
  replicas: {{ default 1 .Values.replicaCount.wordpress }}
  selector:
    matchLabels: { app: wordpress }
  template:
    metadata:
      labels: { app: wordpress }
    spec:
      serviceAccountName: {{ include "webproject.serviceAccountName" . }}
      containers:
      - name: wordpress
        image: {{ printf "%s/%s" .Values.image.registry .Values.image.wordpress }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: "mariadb-service:3306"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dbCredentials.name }}
                key: username
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dbCredentials.name }}
                key: password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dbCredentials.name }}
                key: database
        {{- with (index .Values "resources" "wordpress") }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
